backend:
  name: github
  repo: jschmidtnj/annika.world
  branch: main

site_url: https://annikaworld.netlify.app
display_url: https://annikaworld.netlify.app

locale: en

media_folder: web/content/assets
public_folder: ../assets

collections:
  - name: pages
    label: Pages
    files:
      - label: "About Page"
        name: "about"
        file: "web/content/pages/about.md"
        fields:
          - name: image
            label: Image
            widget: image
          - name: biography
            label: Biography
            widget: markdown
          - name: aboutArt
            label: 'About Art'
            widget: markdown
          - name: education
            label: Education
            widget: markdown
          - name: awards
            label: Awards
            widget: markdown
      - label: "Art Page"
        name: "art"
        file: "web/content/pages/art.md"
        fields:
          - name: images
            label: Images
            widget: list
            fields:
              - name: caption
                label: Caption
                widget: string
              - name: image
                label: Image
                widget: image
              - name: year
                label: Year
                widget: number
                value_type: int
                default: 2023
              - name: width
                label: Width
                widget: number
                value_type: float
                min: 0
                max: 12
                default: 3
